; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_port = /dev/ttyACM2
monitor_speed = 115200

; --- CRITICAL N16R8 MEMORY CONFIGURATION ---
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi 
build_flags = 
    -D BOARD_HAS_PSRAM
; -------------------------------------------

board_build.filesystem = littlefs

lib_deps =
    majicdesigns/MD_Parola @ ^3.7.5
    majicdesigns/MD_MAX72XX @ ^3.5.1
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0 
  
